# Generated by Django 4.1.5 on 2023-02-15 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author_edge',
            name='from_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_from_sub', to='gather.subreddit_result'),
        ),
        migrations.AlterField(
            model_name='author_edge',
            name='to_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_to_sub', to='gather.subreddit_result'),
        ),
        migrations.AlterField(
            model_name='mod_edge',
            name='from_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_from_sub', to='gather.subreddit_result'),
        ),
        migrations.AlterField(
            model_name='mod_edge',
            name='to_sub',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mod_to_sub', to='gather.subreddit_result'),
        ),
    ]
